USE diginamic;

# a
SELECT * FROM ARTICLE;

# b
SELECT REF, DESIGNATION FROM ARTICLE WHERE PRIX > 2;

# c
SELECT * FROM ARTICLE WHERE PRIX >= 2 AND PRIX <= 6.25;

# d
SELECT * FROM ARTICLE WHERE PRIX BETWEEN 2 AND 6.25;

# e
SELECT * FROM ARTICLE WHERE PRIX NOT BETWEEN 2 AND 6.25 AND ID_FOU = 1 ORDER BY PRIX DESC;

# f
SELECT * FROM ARTICLE WHERE ID_FOU = 1 OR ID_FOU = 3;

# g
SELECT * FROM ARTICLE WHERE ID_FOU IN (1, 3);

# h
SELECT * FROM ARTICLE WHERE ID_FOU NOT IN (1, 3);

# i
SELECT * FROM BON WHERE DATE_CMDE BETWEEN '2019-02-01' AND '2019-04-30';
